version: "3"
services:

  ui:
    image: marymahaon/happy-fridge:front-v4.0

  cloud:
    image: marymahaon/happy-fridge:back-v2.4
    environment:
      - SPRING_MAIL_USERNAME=username
      - SPRING_MAIL_PASSWORD=password

  proxy:
    container_name: haproxy
    image: marymahaon/happy-fridge:haproxy
    ports:
      - "80:80"
    depends_on:
      - cloud
      - ui

