version: "3"
services:

  ui:
    image: marymahaon/happy-fridge:test-save

  cloud:
    image: marymahaon/happy-fridge:back-v1
    environment:
      - SPRING_MAIL_USERNAME=username
      - SPEING_MAIL_PASSWORD=password

  proxy:
    container_name: haproxy
    image: marymahaon/happy-fridge:haproxy
    ports:
      - "80:80"
    depends_on:
      - cloud
      - ui

